// Code generated by protoc-gen-go. DO NOT EDIT.
// source: validator.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	anypb "google.golang.org/protobuf/types/known/anypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ValidationError struct {
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	// default_view_msg is the default display message in view(web/app) when an error occurs.
	DefaultViewMsg string `protobuf:"bytes,4,opt,name=default_view_msg,json=defaultViewMsg,proto3" json:"default_view_msg,omitempty"`
	// Describes all violations in a client request.
	FieldViolations      []*ValidationError_FieldViolation `protobuf:"bytes,3,rep,name=field_violations,json=fieldViolations,proto3" json:"field_violations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *ValidationError) Reset()         { *m = ValidationError{} }
func (m *ValidationError) String() string { return proto.CompactTextString(m) }
func (*ValidationError) ProtoMessage()    {}
func (*ValidationError) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf1c6ec7c0d80dd5, []int{0}
}

func (m *ValidationError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidationError.Unmarshal(m, b)
}
func (m *ValidationError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidationError.Marshal(b, m, deterministic)
}
func (m *ValidationError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidationError.Merge(m, src)
}
func (m *ValidationError) XXX_Size() int {
	return xxx_messageInfo_ValidationError.Size(m)
}
func (m *ValidationError) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidationError.DiscardUnknown(m)
}

var xxx_messageInfo_ValidationError proto.InternalMessageInfo

func (m *ValidationError) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ValidationError) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ValidationError) GetDefaultViewMsg() string {
	if m != nil {
		return m.DefaultViewMsg
	}
	return ""
}

func (m *ValidationError) GetFieldViolations() []*ValidationError_FieldViolation {
	if m != nil {
		return m.FieldViolations
	}
	return nil
}

// A message type used to describe a single bad request field.
type ValidationError_FieldViolation struct {
	// A path leading to a field in the request body. The value will be a
	// sequence of dot-separated identifiers that identify a protocol buffer
	// field. E.g., "field_violations.field" would identify this field.
	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Code  string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Param string `protobuf:"bytes,3,opt,name=param,proto3" json:"param,omitempty"`
	// A description of why the request element is bad.
	Msg string `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	// default_view_msg is the default display message in view(web/app) when an error occurs.
	DefaultViewMsg string `protobuf:"bytes,6,opt,name=default_view_msg,json=defaultViewMsg,proto3" json:"default_view_msg,omitempty"`
	// Extension.
	Payload              *anypb.Any `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ValidationError_FieldViolation) Reset()         { *m = ValidationError_FieldViolation{} }
func (m *ValidationError_FieldViolation) String() string { return proto.CompactTextString(m) }
func (*ValidationError_FieldViolation) ProtoMessage()    {}
func (*ValidationError_FieldViolation) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf1c6ec7c0d80dd5, []int{0, 0}
}

func (m *ValidationError_FieldViolation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidationError_FieldViolation.Unmarshal(m, b)
}
func (m *ValidationError_FieldViolation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidationError_FieldViolation.Marshal(b, m, deterministic)
}
func (m *ValidationError_FieldViolation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidationError_FieldViolation.Merge(m, src)
}
func (m *ValidationError_FieldViolation) XXX_Size() int {
	return xxx_messageInfo_ValidationError_FieldViolation.Size(m)
}
func (m *ValidationError_FieldViolation) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidationError_FieldViolation.DiscardUnknown(m)
}

var xxx_messageInfo_ValidationError_FieldViolation proto.InternalMessageInfo

func (m *ValidationError_FieldViolation) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *ValidationError_FieldViolation) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ValidationError_FieldViolation) GetParam() string {
	if m != nil {
		return m.Param
	}
	return ""
}

func (m *ValidationError_FieldViolation) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ValidationError_FieldViolation) GetDefaultViewMsg() string {
	if m != nil {
		return m.DefaultViewMsg
	}
	return ""
}

func (m *ValidationError_FieldViolation) GetPayload() *anypb.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*ValidationError)(nil), "proto.ValidationError")
	proto.RegisterType((*ValidationError_FieldViolation)(nil), "proto.ValidationError.FieldViolation")
}

func init() { proto.RegisterFile("validator.proto", fileDescriptor_bf1c6ec7c0d80dd5) }

var fileDescriptor_bf1c6ec7c0d80dd5 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xcd, 0x6a, 0x83, 0x40,
	0x14, 0x85, 0xf1, 0x2f, 0xa5, 0x37, 0x10, 0x65, 0x70, 0x31, 0xcd, 0x4a, 0x0a, 0x05, 0x57, 0x13,
	0x48, 0x9f, 0xa0, 0x8b, 0x76, 0x57, 0x28, 0x2e, 0xdc, 0xca, 0xa4, 0x33, 0xca, 0xc0, 0xc4, 0x2b,
	0xa3, 0x31, 0xf8, 0x6e, 0x7d, 0xaa, 0x3e, 0x41, 0x71, 0x26, 0x96, 0xa6, 0x94, 0xae, 0xbc, 0xe7,
	0xdc, 0x4f, 0xe6, 0x9c, 0x0b, 0xf1, 0xc8, 0xb5, 0x12, 0x7c, 0x40, 0xc3, 0x3a, 0x83, 0x03, 0x92,
	0xc8, 0x7e, 0xb6, 0x77, 0x0d, 0x62, 0xa3, 0xe5, 0xce, 0xaa, 0xc3, 0xa9, 0xde, 0xf1, 0x76, 0x72,
	0xc4, 0xfd, 0xa7, 0x0f, 0x71, 0xe9, 0xfe, 0x52, 0xd8, 0x3e, 0x1b, 0x83, 0x86, 0x10, 0x08, 0xdf,
	0x51, 0x48, 0xea, 0x65, 0x5e, 0x7e, 0x5b, 0xd8, 0x99, 0x24, 0x10, 0x1c, 0xfb, 0x86, 0xfa, 0xd6,
	0x9a, 0x47, 0x92, 0x43, 0x22, 0x64, 0xcd, 0x4f, 0x7a, 0xa8, 0x46, 0x25, 0xcf, 0xd5, 0xbc, 0x0e,
	0xed, 0x7a, 0x73, 0xf1, 0x4b, 0x25, 0xcf, 0xaf, 0x7d, 0x43, 0xde, 0x20, 0xa9, 0x95, 0xd4, 0xa2,
	0x1a, 0x15, 0x6a, 0xfb, 0x4e, 0x4f, 0x83, 0x2c, 0xc8, 0xd7, 0xfb, 0x07, 0x97, 0x82, 0xfd, 0x4a,
	0xc0, 0x5e, 0x66, 0xbc, 0x5c, 0xe8, 0x22, 0xae, 0xaf, 0x74, 0xbf, 0xfd, 0xf0, 0x60, 0x73, 0xcd,
	0x90, 0x14, 0x22, 0x4b, 0x5d, 0x52, 0x3b, 0xf1, 0x5d, 0xc5, 0xff, 0x51, 0x25, 0x85, 0xa8, 0xe3,
	0x86, 0x1f, 0x69, 0xe0, 0x48, 0x2b, 0x96, 0x82, 0xe1, 0xff, 0x05, 0x57, 0x7f, 0x16, 0x64, 0x70,
	0xd3, 0xf1, 0x49, 0x23, 0x17, 0x34, 0xca, 0xbc, 0x7c, 0xbd, 0x4f, 0x99, 0xbb, 0x38, 0x5b, 0x2e,
	0xce, 0x9e, 0xda, 0xa9, 0x58, 0xa0, 0xc3, 0xca, 0xda, 0x8f, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x86, 0x98, 0x6b, 0x2a, 0xb0, 0x01, 0x00, 0x00,
}
